### ISSUE TITLE
执行wp2vite init报错

### ISSUE THREAD

**Issue by gitsheny** [tnfe/wp2vite#10]
[wp2vite-start]:wp2vite认为是Vue项目 [wp2vite-error]:The "path" argument must be of type string. Received undefined

请问这个怎么解决？

**Comment by dravenww** [comment]
可否提供一下demo？

**Comment by gitsheny** [comment]
> 可否提供一下demo？

公司的项目，不方便诶

**Comment by VCcome** [comment]
[wp2vite-error]:The "id" argument must be of type string. Received type boolean

**Comment by lzw10168** [comment]
[wp2vite-params]:unknow config for your project 报这个错是项目不支持吗？

**Comment by lzw10168** [comment]
项目是webpack-dev-server

**Comment by dravenww** [comment]
安装最新版本，2.0.1 试下
