### ISSUE TITLE
wp2vite --config ./webpack.config.js

### ISSUE THREAD

**Issue by 273403986** [tnfe/wp2vite#11]
[wp2vite-error]:为获取到配置文件，请用参数输入 --config

**Comment by dravenww** [comment]
可以提供下demo吗？

**Comment by dekuofa1995** [comment]
> 可以提供下demo吗？

![image](https://user-images.githubusercontent.com/56107353/119758904-e4c18300-bed9-11eb-878f-767628b60a5f.png)
这里的参数没往下传，方法内部也要对应修改一下

**Comment by dravenww** [comment]
> > 可以提供下demo吗？
> 
> ![image](https://user-images.githubusercontent.com/56107353/119758904-e4c18300-bed9-11eb-878f-767628b60a5f.png)
> 这里的参数没往下传，方法内部也要对应修改一下

可以提供下demo吗？是用什么创建的项目呢？

**Comment by dravenww** [comment]
安装最新版本，2.0.1试下
