### ISSUE TITLE
wp2vite command not found

### ISSUE THREAD

**Issue by smileyby** [tnfe/wp2vite#12]
npm i -g wp2vite
cd your_workspace/your_project
wp2vite  报错：command not found

**Comment by dravenww** [comment]
提供下截图？

**Comment by smileyby** [comment]
这个是由于我本地 环境变量 没有npm导致的，已解决
现在 wp2vite init 报 The "id" argument must be of type string. Received type boolean

**Comment by sisisiss** [comment]
找不到是因为路径不对
