### ISSUE TITLE
是否支持vue-cli2初始化的项目？

### ISSUE THREAD

**Issue by BryanAdamss** [tnfe/wp2vite#16]
作者你好：
 
有两个问题想请教
1. wp2vite是否支持使用vue-cli2初始化的项目迁移？
2. 迁移后的项目是否开发、生产都使用的vite生态？
2. 如果只将vite当作开发服务器使用，生产环境依然使用webpack打包，wp2vite是否支持？如果不支持，自行改造工作可大？

**Comment by dravenww** [comment]
你好，我一一回答下你的问题。
1、vue-cli2生成的项目，如果没有被改造过、编码正常的话，应该是可以支持的
2、迁移后的项目还是可以继续使用之前的配置进行开发和生产，wp2vite只是在你的项目中加入了vite等的配置，不会改变你项目的内容，也不会删除之前webpack等的依赖
3、在上面2中已经说明了，不会改变你的项目，所以你可以保持继续使用webpack为生产环境打包，开发环境使用vite；wp2vite只是一个转换工具，不同的项目会有不同的情况，如果wp2vite帮助不到你的话，自行改造成本也不会很大。

以上是我的个人建议，如有问题，欢迎沟通。

**Comment by BryanAdamss** [comment]
感谢回复！

似乎不支持`cli2`初始化的项目，不知道是不是我用的不对，报`unknow config for your project`错误，可能是`cli2`项目没有安装`@vue/cli-service`，导致`doVue`方法没走到；
https://github.com/tnfe/wp2vite/blob/18aa1c84049558eba550850bd539de63edc9c7b0/src/main/start.js#L22

**Comment by dravenww** [comment]
可否提供下项目demo，我们看下？

**Comment by BryanAdamss** [comment]
内部代码，可能无法直接上传，但项目结构和这个`repo`是一样的，可以参考这个`demo`
`https://github.com/BryanAdamss/vue-awesome-template/tree/cli-2.x`

**Comment by dravenww** [comment]
> 内部代码，可能无法直接上传，但项目结构和这个`repo`是一样的，可以参考这个`demo`
> `https://github.com/BryanAdamss/vue-awesome-template/tree/cli-2.x`

这个项目clone下来后，跑不起来.

**Comment by BryanAdamss** [comment]
> > 内部代码，可能无法直接上传，但项目结构和这个`repo`是一样的，可以参考这个`demo`
> > `https://github.com/BryanAdamss/vue-awesome-template/tree/cli-2.x`
> 
> 这个项目clone下来后，跑不起来.

是不是node版本不对？切到8.17试试

**Comment by dravenww** [comment]
> > > 内部代码，可能无法直接上传，但项目结构和这个`repo`是一样的，可以参考这个`demo`
> > > `https://github.com/BryanAdamss/vue-awesome-template/tree/cli-2.x`
> > 
> > 
> > 这个项目clone下来后，跑不起来.
> 
> 是不是node版本不对？切到8.17试试

看了下项目，应该是转了后也不能直接运行，需要对项目进行改造，引用vue的文件目前都是省略后缀的，使用vite的时候不能省略vue的后缀；可能还有其他需要改造的地方。

**Comment by BryanAdamss** [comment]
> > > > 内部代码，可能无法直接上传，但项目结构和这个`repo`是一样的，可以参考这个`demo`
> > > > `https://github.com/BryanAdamss/vue-awesome-template/tree/cli-2.x`
> > > 
> > > 
> > > 这个项目clone下来后，跑不起来.
> > 
> > 
> > 是不是node版本不对？切到8.17试试
> 
> 看了下项目，应该是转了后也不能直接运行，需要对项目进行改造，引用vue的文件目前都是省略后缀的，使用vite的时候不能省略vue的后缀；可能还有其他需要改造的地方。

嗯，我再试试；
我最近写了个[add-vue-suffix](https://www.npmjs.com/package/add-vue-suffix)，可以补齐`vue`后缀，正好用上了😂
