### ISSUE TITLE
webpack配置文件路径问题

### ISSUE THREAD

**Issue by ramocky** [tnfe/wp2vite#18]
我的webpack配置文件夹不在根目录,在build文件夹下，执行命令出现：
[wp2vite-env]:开始分析项目属性
[wp2vite-env]:项目属性分析完成
[wp2vite-webpack]:未传递webpack配置文件路径
如何解决这个问题？

**Comment by dravenww** [comment]
> 我的webpack配置文件夹不在根目录,在build文件夹下，执行命令出现：
> [wp2vite-env]:开始分析项目属性
> [wp2vite-env]:项目属性分析完成
> [wp2vite-webpack]:未传递webpack配置文件路径
> 如何解决这个问题？

请问你是什么项目？可以提供个demo吗？

**Comment by exposir** [comment]
> > 我的webpack配置文件夹不在根目录,在build文件夹下，执行命令出现：
> > [wp2vite-env]:开始分析项目属性
> > [wp2vite-env]:项目属性分析完成
> > [wp2vite-webpack]:未传递webpack配置文件路径
> > 如何解决这个问题？
> 
> 请问你是什么项目？可以提供个demo吗？


![image](https://user-images.githubusercontent.com/33340988/128116756-ea394bcd-f95b-4866-b4fb-91e9760b641d.png)

遇到了同样的问题

**Comment by exposir** [comment]
> > 我的webpack配置文件夹不在根目录,在build文件夹下，执行命令出现：
> > [wp2vite-env]:开始分析项目属性
> > [wp2vite-env]:项目属性分析完成
> > [wp2vite-webpack]:未传递webpack配置文件路径
> > 如何解决这个问题？
> 
> 请问你是什么项目？可以提供个demo吗？

![image](https://user-images.githubusercontent.com/33340988/128117491-4e6aa15b-6348-4c60-bde9-61a3cf078dca.png)

遇到了同样的问题

**Comment by dravenww** [comment]
wp2vite --config=./webpack.config.js
试下这个命令
