### ISSUE TITLE
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by ghostman-git** [tnfe/wp2vite#2]
npm run dev  

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序

**Comment by dravenww** [comment]
windows环境下的吗？可以在scripts里面加下cross-env

**Comment by ghostman-git** [comment]
> windows环境下的吗？可以在scripts里面加下cross-env

已解决
