### ISSUE TITLE
请问这个问题产生的原因是什么呢

### ISSUE THREAD

**Issue by xiexiaopeng** [tnfe/wp2vite#20]
![image](https://user-images.githubusercontent.com/36291548/128156841-b7e7fa62-1a53-4519-bb3e-7c4748b1a4db.png)

**Comment by xiexiaopeng** [comment]
我应该怎么排查这个问题在哪出现的，也没有个错误指向

**Comment by dravenww** [comment]
可以提供下项目demo吗

**Comment by wangzhengbo** [comment]
我提了pull request https://github.com/tnfe/wp2vite/pull/24

**Comment by dravenww** [comment]
安装最新版本： 2.0.2，已修复此问题
