### ISSUE TITLE
执行时候出错UnhandledPromiseRejectionWarning: TypeError: Unexpected MODIFIER at 30, expected END

### ISSUE THREAD

**Issue by pengyanxue** [tnfe/wp2vite#21]
执行 npm run vite-dev 后显示启动成功 
一访问就报这个错了
![image](https://user-images.githubusercontent.com/17831538/128956689-9aaf01f0-7da2-4593-ac27-cc21881c2287.png)
还有如果是多入口的话，这个还是一样的使用吗？
还需要配置什么吗？

**Comment by dravenww** [comment]
可以去 https://github.com/vitejs/vite 这里看看
