### ISSUE TITLE
e is not a function

### ISSUE THREAD

**Issue by gp3098** [tnfe/wp2vite#23]
初始化的时候提示的错误e is not a function
使用的是react-app-rewired

**Comment by gp3098** [comment]
[wp2vite-env]:开始分析项目属性
[wp2vite-env]:项目属性分析完成
[wp2vite-error]:TypeError: e is not a function

**Comment by gp3098** [comment]
[wp2vite-env]:开始分析项目属性
[wp2vite-env]:项目属性分析完成
[wp2vite-error]:TypeError: e is not a function

**Comment by gp3098** [comment]
```[wp2vite-env]:开始分析项目属性
[wp2vite-env]:项目属性分析完成
[wp2vite-error]:TypeError: e is not a function```

**Comment by wangzhengbo** [comment]
碰到同样的问题

**Comment by wangzhengbo** [comment]
我提了pull request https://github.com/tnfe/wp2vite/pull/24

**Comment by dravenww** [comment]
bug，已修复，版本：2.0.2
