### ISSUE TITLE
create react app(使用了react-app-rewired)应用转化后jsx语法不支持

### ISSUE THREAD

**Issue by wangzhengbo** [tnfe/wp2vite#25]
[plugin:vite-plugin-importer] unknown: Support for the experimental syntax 'jsx' isn't currently enabled (27:3):

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

**Comment by dravenww** [comment]
请提供一下vite的配置或者项目demo

**Comment by dravenww** [comment]
可以更新wp2vite的最新版本，再试下，最新版本是：2.0.5

**Comment by hbxks18** [comment]
我也是，转jsx报错。
我转完之后的config文件，而且这些依赖没有自动添加到package里的，我手动安装的，然后index.html的入口文件也是我自己的添加的，不知道有没有关系，辛苦作者看看哈。
`/* eslint-disable */
import legacyPlugin from '@vitejs/plugin-legacy';
import usePluginImport from 'vite-plugin-importer';
import {
  viteMockServe
} from 'vite-plugin-mock';
import * as path from 'path';
import reactRefresh from '@vitejs/plugin-react-refresh';
// @see https://cn.vitejs.dev/config/
export default ({
  command,
  mode
}) => {
  let rollupOptions = {};


  let optimizeDeps = {};


  let alias = {}

  let proxy = {}

  let define = {
    'process.env.APP_IS_LOCAL': '"true"',
  }

  let esbuild = {}

  return {
    base: './', // index.html文件所在位置
    root: './', // js导入的资源路径，src
    resolve: {
      alias,
    },
    define: define,
    server: {
      // 代理
      proxy,
    },
    build: {
      target: 'es2015',
      minify: 'terser', // 是否进行压缩,boolean | 'terser' | 'esbuild',默认使用terser
      manifest: false, // 是否产出maifest.json
      sourcemap: false, // 是否产出soucemap.json
      outDir: 'build', // 产出目录
      rollupOptions,
    },
    esbuild,
    optimizeDeps,
    plugins: [
      legacyPlugin({
        targets: ['Android > 39', 'Chrome >= 60', 'Safari >= 10.1', 'iOS >= 10.3', 'Firefox >= 54', 'Edge >= 15'],
      }), usePluginImport({
        libraryName: " ", // todo please input your babel-plugin-import config
        libraryDirectory: " ",
        style: "css",
      }), viteMockServe({
        mockPath: 'mock',
        localEnabled: command === 'serve',
      }), reactRefresh(),
    ],
    css: {
      preprocessorOptions: {
        less: {
          // 支持内联 JavaScript
          javascriptEnabled: true,
        }
      }
    },
  }
}`

**Comment by dravenww** [comment]
> 我也是，转jsx报错。
> 我转完之后的config文件，而且这些依赖没有自动添加到package里的，我手动安装的，然后index.html的入口文件也是我自己的添加的，不知道有没有关系，辛苦作者看看哈。
> `/* eslint-disable */
> import legacyPlugin from '@vitejs/plugin-legacy';
> import usePluginImport from 'vite-plugin-importer';
> import {
> viteMockServe
> } from 'vite-plugin-mock';
> import * as path from 'path';
> import reactRefresh from '@vitejs/plugin-react-refresh';
> // @see https://cn.vitejs.dev/config/
> export default ({
> command,
> mode
> }) => {
> let rollupOptions = {};
> 
> let optimizeDeps = {};
> 
> let alias = {}
> 
> let proxy = {}
> 
> let define = {
> 'process.env.APP_IS_LOCAL': '"true"',
> }
> 
> let esbuild = {}
> 
> return {
> base: './', // index.html文件所在位置
> root: './', // js导入的资源路径，src
> resolve: {
> alias,
> },
> define: define,
> server: {
> // 代理
> proxy,
> },
> build: {
> target: 'es2015',
> minify: 'terser', // 是否进行压缩,boolean | 'terser' | 'esbuild',默认使用terser
> manifest: false, // 是否产出maifest.json
> sourcemap: false, // 是否产出soucemap.json
> outDir: 'build', // 产出目录
> rollupOptions,
> },
> esbuild,
> optimizeDeps,
> plugins: [
> legacyPlugin({
> targets: ['Android > 39', 'Chrome >= 60', 'Safari >= 10.1', 'iOS >= 10.3', 'Firefox >= 54', 'Edge >= 15'],
> }), usePluginImport({
> libraryName: " ", // todo please input your babel-plugin-import config
> libraryDirectory: " ",
> style: "css",
> }), viteMockServe({
> mockPath: 'mock',
> localEnabled: command === 'serve',
> }), reactRefresh(),
> ],
> css: {
> preprocessorOptions: {
> less: {
> // 支持内联 JavaScript
> javascriptEnabled: true,
> }
> }
> },
> }
> }`

可以看下wp2vite的版本： wp2vite -v ；如果版本不是2.0.5的话，可以升级后再试下。

**Comment by hbxks18** [comment]
> > 我也是，转jsx报错。
> > 我转完之后的config文件，而且这些依赖没有自动添加到package里的，我手动安装的，然后index.html的入口文件也是我自己的添加的，不知道有没有关系，辛苦作者看看哈。
> > `/* eslint-disable */
> > import legacyPlugin from '@vitejs/plugin-legacy';
> > import usePluginImport from 'vite-plugin-importer';
> > import {
> > viteMockServe
> > } from 'vite-plugin-mock';
> > import * as path from 'path';
> > import reactRefresh from '@vitejs/plugin-react-refresh';
> > // @see https://cn.vitejs.dev/config/
> > export default ({
> > command,
> > mode
> > }) => {
> > let rollupOptions = {};
> > let optimizeDeps = {};
> > let alias = {}
> > let proxy = {}
> > let define = {
> > 'process.env.APP_IS_LOCAL': '"true"',
> > }
> > let esbuild = {}
> > return {
> > base: './', // index.html文件所在位置
> > root: './', // js导入的资源路径，src
> > resolve: {
> > alias,
> > },
> > define: define,
> > server: {
> > // 代理
> > proxy,
> > },
> > build: {
> > target: 'es2015',
> > minify: 'terser', // 是否进行压缩,boolean | 'terser' | 'esbuild',默认使用terser
> > manifest: false, // 是否产出maifest.json
> > sourcemap: false, // 是否产出soucemap.json
> > outDir: 'build', // 产出目录
> > rollupOptions,
> > },
> > esbuild,
> > optimizeDeps,
> > plugins: [
> > legacyPlugin({
> > targets: ['Android > 39', 'Chrome >= 60', 'Safari >= 10.1', 'iOS >= 10.3', 'Firefox >= 54', 'Edge >= 15'],
> > }), usePluginImport({
> > libraryName: " ", // todo please input your babel-plugin-import config
> > libraryDirectory: " ",
> > style: "css",
> > }), viteMockServe({
> > mockPath: 'mock',
> > localEnabled: command === 'serve',
> > }), reactRefresh(),
> > ],
> > css: {
> > preprocessorOptions: {
> > less: {
> > // 支持内联 JavaScript
> > javascriptEnabled: true,
> > }
> > }
> > },
> > }
> > }`
> 
> 可以看下wp2vite的版本： wp2vite -v ；如果版本不是2.0.5的话，可以升级后再试下。

是的，版本是最新的的。排查下了原因：
应该是js文件使用了jsx语法，这个是官方不支持的
https://github.com/vitejs/vite/discussions/3448#discussioncomment-749919

**Comment by hbxks18** [comment]
@wangzhengbo 可以试一下 https://github.com/vitejs/vite/discussions/3448#discussioncomment-749919
