### ISSUE TITLE
vue3使用时判断当前项目为vue2

### ISSUE THREAD

**Issue by see-the-day** [tnfe/wp2vite#27]
1.compareVersion('3.0.0','2.0.0')判断有问题
2.getProType判断版本有问题
prepareEnv 方法里面用checkVueVersion来判断env.isVue2是否为true，当前版本为3.0.0，即compareVersion('3.0.0','2.0.0')结果也是true，并且getProType方法判断当前项目当env.isVue2为true时，就判断当前项目为vue2了

**Comment by lnyie** [comment]
// import {
//   createVuePlugin
// } from 'vite-plugin-vue2';
把这段引入去掉, 并把下边的createVuePlugin(), 直接删掉, 就能启动了

**Comment by dravenww** [comment]
> 1.compareVersion('3.0.0','2.0.0')判断有问题
> 2.getProType判断版本有问题
> prepareEnv 方法里面用checkVueVersion来判断env.isVue2是否为true，当前版本为3.0.0，即compareVersion('3.0.0','2.0.0')结果也是true，并且getProType方法判断当前项目当env.isVue2为true时，就判断当前项目为vue2了

bug，下个版本，我修复一下

**Comment by dravenww** [comment]
已经修复，安装最新版本即可使用
