### ISSUE TITLE
Unrestricted file system access to "/es6-promise"

### ISSUE THREAD

**Issue by Dr294769070** [tnfe/wp2vite#28]
npm run vite-start，控制台出现warn：Unrestricted file system access to "/es6-promise"

打开浏览器看到http://localhost:3000/es6-promise  状态为404NotFound。

尝试修改vite.config.js
`
server: {
    fs: {
        allow: ['..', '/es6-promise']
    }
}
`
不过没有效果，想问下这个问题怎么解决

**Comment by dravenww** [comment]
这是vite的问题，可以参考下这个：https://github.com/vitejs/vite/issues/506

**Comment by Dr294769070** [comment]
> 这是vite的问题，可以参考下这个：[vitejs/vite#506](https://github.com/vitejs/vite/issues/506)

thanks
