### ISSUE TITLE
不支持svg, 直接报错

### ISSUE THREAD

**Issue by gxlself** [tnfe/wp2vite#29]
![image](https://user-images.githubusercontent.com/32733844/130005837-5b386bac-2518-4e7a-88e7-12220ffac37a.png)

**Comment by dravenww** [comment]
可以试试这个插件：https://github.com/anncwb/vite-plugin-svg-icons

**Comment by dravenww** [comment]
因长时间不回复，暂时关闭此issue，如有问题，可reopen。
