### ISSUE TITLE
script-loader!   worker-loader!

### ISSUE THREAD

**Issue by ghostman-git** [tnfe/wp2vite#3]
script-loader!  
worker-loader!

**Comment by dravenww** [comment]
可否详细描述下你的问题？

**Comment by ghostman-git** [comment]
> 可否详细描述下你的问题？

var PdfjsWorker = require('worker-loader!./pdf.worker.js');
npm run dev 会报错
![image](https://user-images.githubusercontent.com/13376074/116329606-4ec50a80-a7fe-11eb-9f5d-b11dbe25a5b7.png)

**Comment by dravenww** [comment]
应该是vite解析不了这样的引用路径导致的，vite目前不支持这样的引用方式

**Comment by IndexXuan** [comment]
vite 支持 可以加上?worker 查询字符串，详情看 vite 官网

**Comment by dravenww** [comment]
> vite 支持 可以加上?worker 查询字符串，详情看 vite 官网

你说的是这个吗？https://cn.vitejs.dev/guide/features.html#web-workers
这应该是脚本文件，不是上面用worker-loader去加载pdf.worker.js。
还是说是这个？https://cn.vitejs.dev/guide/assets.html#importing-asset-as-url
这个可能能够满足要求

**Comment by IndexXuan** [comment]
嗯嗯 总之有等价物

**Comment by aafnnp** [comment]
> > 可否详细描述下你的问题？
> 
> var PdfjsWorker = require('worker-loader!./pdf.worker.js');
> npm run dev 会报错
> ![image](https://user-images.githubusercontent.com/13376074/116329606-4ec50a80-a7fe-11eb-9f5d-b11dbe25a5b7.png)

这个问题最后怎么解决的？

**Comment by dravenww** [comment]
import PdfjsWorker from './pdf.worker.js?worker'

改为这样试下呢？详情看下https://cn.vitejs.dev/guide/assets.html#importing-script-as-a-worker

**Comment by ghostman-git** [comment]
> > > 可否详细描述下你的问题？
> > 
> > 
> > var PdfjsWorker = require('worker-loader!./pdf.worker.js');
> > npm run dev 会报错
> > ![image](https://user-images.githubusercontent.com/13376074/116329606-4ec50a80-a7fe-11eb-9f5d-b11dbe25a5b7.png)
> 
> 这个问题最后怎么解决的？

就项目转的过程中各种问题太痛快了...   然后没再继续

**Comment by aafnnp** [comment]
> > > > 可否详细描述下你的问题？
> > > 
> > > 
> > > var PdfjsWorker = require('worker-loader!./pdf.worker.js');
> > > npm run dev 会报错
> > > ![image](https://user-images.githubusercontent.com/13376074/116329606-4ec50a80-a7fe-11eb-9f5d-b11dbe25a5b7.png)
> > 
> > 
> > 这个问题最后怎么解决的？
> 
> 就项目转的过程中各种问题太痛快了... 然后没再继续

推到重来？

**Comment by ghostman-git** [comment]
> > > > > 可否详细描述下你的问题？
> > > > 
> > > > 
> > > > var PdfjsWorker = require('worker-loader!./pdf.worker.js');
> > > > npm run dev 会报错
> > > > ![image](https://user-images.githubusercontent.com/13376074/116329606-4ec50a80-a7fe-11eb-9f5d-b11dbe25a5b7.png)
> > > 
> > > 
> > > 这个问题最后怎么解决的？
> > 
> > 
> > 就项目转的过程中各种问题太痛快了... 然后没再继续
> 
> 推到重来？

没再继续，后期有时间或成熟些再搞吧

**Comment by dravenww** [comment]
暂时关闭，有其他问题的话，请重开issue
