### ISSUE TITLE
不支持webpack在index.html直接写入处理

### ISSUE THREAD

**Issue by gxlself** [tnfe/wp2vite#30]
![image](https://user-images.githubusercontent.com/32733844/130005916-1fd4d844-f14c-4085-9c56-8f430170dc7c.png)

![image](https://user-images.githubusercontent.com/32733844/130005958-19501dca-a97a-4d6f-8371-4ee632b31925.png)

**Comment by dravenww** [comment]
https://github.com/vitejs/awesome-vite
这里有你需要的插件

**Comment by dravenww** [comment]
https://github.com/ahwgs/vite-plugin-html-config
https://github.com/rollup/plugins/tree/master/packages/html
试下这两个插件，不过可能不能类似webpack的方式在HTML中使用了。
