### ISSUE TITLE
vue-loader requires @vue/compiler-sfc to be present in the dependency tree

### ISSUE THREAD

**Issue by matedmzy1124** [tnfe/wp2vite#36]
原本package.json内只有stylus-loader": "^3.0.2","vue-style-loader": "^4.1.2",转化完成后报错
Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree

**Comment by dravenww** [comment]
请问是怎么启动的呢？vite不需要vue-loader了呀

**Comment by dravenww** [comment]
久未回复，先关闭了，如有问题，可reopen
