### ISSUE TITLE
vite-plugin-vue2 Problem | vite-plugin-vue2 问题

### ISSUE THREAD

**Issue by FoundTheWOUT** [tnfe/wp2vite#37]
你好, 在`vue2`项目中, 你把`vite-plugin-vue2`插到了`plugin`的最后一位. 我不是很清楚`rollup`中插件的加载顺序. 但经过我调试, 如果把`vue2`插件放在最后一位会导致各种问题, 当我尝试把插件移到数组第一位时, 问题就完全解决了.
👇当插件在最后一位时
![屏幕截图 2021-08-28 001038](https://user-images.githubusercontent.com/47922588/131157095-0ad7b082-ba62-420c-a8b7-850aa6a96cb8.png)

**Comment by dravenww** [comment]
2.0.7版本已经修复，感谢指出：[wp2vite@2.0.7](https://www.npmjs.com/package/wp2vite/v/2.0.7)
