### ISSUE TITLE
webpack react项目 转化后 不识别< 标签前缀 与... 请问是什么原因？

### ISSUE THREAD

**Issue by YunFan68** [tnfe/wp2vite#40]
![1630565573591](https://user-images.githubusercontent.com/16872131/131796693-a6f156c0-f9aa-477e-9a79-ac9a230bf847.jpg)

**Comment by octopustail** [comment]
试试这个：
[vite-plugin-react-js-support](https://www.npmjs.com/package/vite-plugin-react-js-support)
> vite对jsx语法只认tsx和jsx后缀的文件，可是项目中有很多js类型的文件也是jsx；

**Comment by YunFan68** [comment]
好的 谢谢大佬 我试试
