### ISSUE TITLE
ruoyi-vue 项目无法正常启动 报错

### ISSUE THREAD

**Issue by liangbaika** [tnfe/wp2vite#5]
![image](https://user-images.githubusercontent.com/33059022/116355799-f5280480-a82c-11eb-98ff-f46a1a6350ec.png)

**Comment by dravenww** [comment]
可以贴一下你的项目目录吗？最好是可以精确到此处引用的文件粒度

**Comment by IndexXuan** [comment]
import vue 文件必须带有 .vue 后缀

**Comment by liangbaika** [comment]
有啥好的解决方案没啊

**Comment by dravenww** [comment]
给个demo？

**Comment by IndexXuan** [comment]
你俩为啥不信我说的，上面报错就是 import 要加 .vue 后缀

**Comment by dravenww** [comment]
我是信你的，不过我感觉他引用的不是vue文件，如果是引用的vue文件的话，在不改动项目的基础上，可以加个插件来实现。

**Comment by IndexXuan** [comment]
这引用的显然是 vue 文件。且 vite 不支持不加 vue 后缀，vue-cli 也推荐加，vue-cli 5.x 也是必须加。理由就是决定是否编译 Vue SFC 靠文件后缀，不再检测内容，为了速度

**Comment by dravenww** [comment]
如果这是jsx语法的呢？为什么只有detailTitle的引用报错了，前面两个没有报错呢？我认为这需要提供一个代码目录截图或者demo，来确认一下到底问题出在哪里

**Comment by IndexXuan** [comment]
有道理 而且这个还不是用的 alias @.
不过这用户逼逼叨半天也不给个复现代码，也是醉了

**Comment by liangbaika** [comment]
把这个项目拉下来试一试就知道了呀

**Comment by dravenww** [comment]
> 把这个项目拉下来试一试就知道了呀

哪个项目？地址给下？

**Comment by liangbaika** [comment]
https://gitee.com/y_project/RuoYi-Vue?_from=gitee_search

**Comment by liangbaika** [comment]
https://gitee.com/y_project/RuoYi-Vue/tree/master/ruoyi-ui

**Comment by liangbaika** [comment]
@dravenww

**Comment by liangbaika** [comment]
大佬 有试过吗

**Comment by dravenww** [comment]
你提供的demo，没有看到截图所对应的代码

**Comment by liangbaika** [comment]
那这个demo你那边能跑起来吗 使用vite后

**Comment by dravenww** [comment]
你这个项目需要改造下才能跑起来，这个项目跑不起来的原因是 @IndexXuan 所说的引用vue文件须加上.vue的后缀。

**Comment by dravenww** [comment]
暂时先关闭此issue了，如有问题，可重新提交
