### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by myinlg** [tnfe/wp2vite#6]
![image](https://user-images.githubusercontent.com/37045183/117095304-9b798a00-ad98-11eb-9877-247c9c94dd60.png)
项目中大量存在require语法，包括图片的和第三方库的引入，在尽量少修改原有代码的基础上有什么好的办法吗

**Comment by dravenww** [comment]
有，得自己实现个插件，把代码中的require替换成import，然后再交给vite处理

**Comment by myinlg** [comment]
![微信截图_20210516181852](https://user-images.githubusercontent.com/37045183/118393814-97d8e380-b673-11eb-879d-9ace9220d18d.png)
这种直接写在标签里的不好处理吧

**Comment by dravenww** [comment]
这样的引用没法处理，可以import为一个变量，然后再使用变量
