### ISSUE TITLE
如何指定webpack配置文件

### ISSUE THREAD

**Issue by leohai** [tnfe/wp2vite#9]
<img width="322" alt="截屏2021-05-16 下午4 10 13" src="https://user-images.githubusercontent.com/34530234/118390353-33ad2400-b661-11eb-9e75-7d2965f1692d.png">
当webpack配置文件不在根目录，如何指定对应的webpack文件生成vite config

**Comment by dravenww** [comment]
不好意思，目前暂时不支持这个功能，不过这个功能快开发完了
可以提供一下项目的demo吗？
